# Generated by Django 5.2.1 on 2025-06-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email контакта",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Страна контакта",
                        max_length=100,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Город контакта",
                        max_length=100,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Улица контакта",
                        max_length=100,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        help_text="Номер дома контакта",
                        max_length=20,
                        verbose_name="Номер дома",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
