# Generated by Django 5.2.1 on 2025-06-01 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_platform", "0002_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название сети",
                        max_length=254,
                        verbose_name="Название",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Розничная сеть"),
                            (2, "Индивидуальный предприниматель"),
                        ],
                        help_text="Уровень в иерархии",
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Задолженность перед поставщиком",
                        max_digits=12,
                        verbose_name="Задолженность",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания сети",
                        verbose_name="Дата созданя",
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        help_text="Контакты сети",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node",
                        to="trading_platform.contact",
                        verbose_name="Контакты сети",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Основатель сети",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_nodes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Основатель",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="Продукты сети",
                        to="trading_platform.product",
                        verbose_name="Продукты сети",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Поставщик продукции",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_platform.networknode",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
    ]
